### ISSUE TITLE
Downloading chapters marks them as read on Mangadex

### ISSUE THREAD

**Issue by fma16** [FaizanDurrani/MDReader-Builds#15]
When you download chapters from the chapter list, this marks them as read even if you didn't read them either on the app or on MangaDex.

**Comment by FaizanDurrani** [comment]
MD implemented auto read marking whenever a chapter is grabbed via the api, I can't really do much about this. Will try asking MD devs to fix

**Comment by FaizanDurrani** [comment]
Okay might be able to fix this in the next build
