### ISSUE TITLE
ui feedback

### ISSUE THREAD

**Issue by dg2894** [FaizanDurrani/MDReader-Builds#17]
i spend a lot of time working with ui/ux at my company for our platform so i thought i'd share some feedback, but feel free to ignore this and close the ticket if you don't agree. also, i'm sorry if i annoy you by being too nitpicky. thank you so much for making this app - it's beautiful and a lifesaver!

![feedback copy](https://user-images.githubusercontent.com/25352915/78170171-68cbc800-7407-11ea-8432-da7aaa3e6515.png)

**Comment by FaizanDurrani** [comment]
Appreciate the advice, will look into the things outlined. Feel free to post more if you want.
