### ISSUE TITLE
Advanced search multiple tags

### ISSUE THREAD

**Issue by Microscale** [FaizanDurrani/MDReader-Builds#2]
When using the advanced search feature, I’m attempting to search for manga with more than one tag but it comes up with popular manga of only one category. When I deselect the tags leaving only one left it works and I can view that tag but when I search for additional tags it only comes up with the one option.

**Comment by FaizanDurrani** [comment]
Have you tried changing the inclusion mode?

**Comment by Microscale** [comment]
Yeah, that sorted it. It’s a little confusing though because you are able to select multiple tags without toggling the inclusion mode. I’ve probably just used MR too long 😅
