### ISSUE TITLE
Reader login problem

### ISSUE THREAD

**Issue by GeoferythePig** [FaizanDurrani/MDReader-Builds#27]
Whenever I go to https://faizandurrani.github.io/MR-to-MangaDex/ and sign in, all that happens is that it brings me to a white page with "Error 405" on it. I'm not sure if this is the right place to report this issue.

**Comment by FaizanDurrani** [comment]
This repo is specifically for issues with the iphone build of Paper Reader. Post issues with MR exporter on Discord.

Also, use Chrome on Desktop.
