### ISSUE TITLE
[BUG] Chapter tracking not working

### ISSUE THREAD

**Issue by Supster131** [FaizanDurrani/MDReader-Builds#39]
**Describe the bug**
After reading a chapter of a manga, it is not being marked as read both in the app and on MangaDex.

**To Reproduce**
Read a chapter of a manga.

**Expected behaviour**
After reading a chapter, it should be marked as read.

**App Version**
v0.2-wip.4

**Comment by FaizanDurrani** [comment]
It marks chapters read when the last page appears, you're probably closing the reader earlier

**Comment by FaizanDurrani** [comment]
Was able to reproduce it with Paged reader, seems to not be present in Longstrip reader
