### ISSUE TITLE
[BUG] Manga syncing still partially broken

### ISSUE THREAD

**Issue by Supster131** [FaizanDurrani/MDReader-Builds#40]
**Describe the bug**
Sometimes an unfollowed manga on MangaDex will show up as followed on the app, while a followed manga on MangaDex will show up as unfollowed. Attempting to sync manually will keep asking if you want follow/unfollow locally are on MangaDex, these options do nothing.

**To Reproduce**
Due to the radical nature of this bug, it might be difficult/different for others to reproduce. How I got it to occur was follow a manga on the app, then follow a different manga on MangaDex, then attempt a sync.

**Expected behaviour**
Following a manga on MangaDex or on the app should follow it on the other after a sync, while unfollowing a manga on MangaDex or the app should unfollow it on the other after a sync.

**App Version**
v0.2-wip.4

**Comment by FaizanDurrani** [comment]
The changes to a user's list aren't instantly reflected by the follows api so there's a delay of like 5 mins before the api correctly reports the user's list.

**Comment by MoaYenrai** [comment]
I have the same/ a similar behavior. When I sync my followlist, I get the message: "You have 1 manga (s) that are not followed locally". However, a click on "Follow locally" is useless because the message  reappears every time I sync.

**Comment by FaizanDurrani** [comment]
> I have the same/ a similar behavior. When I sync my followlist, I get the message: "You have 1 manga (s) that are not followed locally". However, a click on "Follow locally" is useless because the message reappears every time I sync.

Double check that all your mangas are in proper lists on MD. A couple builds back unfollow was broken and was putting mangas into a non-existing list on MD

**Comment by MoaYenrai** [comment]
I just recorded the message when unfollowing it on MD to find out the ID of the manga. Apparently the Manga on MangaDex was deleted, because I can no longer access it. It was still on my reading list.

It was:
https://mangadex.org/title/42110/the-archmage-s-daughter

**Comment by FaizanDurrani** [comment]
> I just recorded the message when unfollowing it on MD to find out the ID of the manga. Apparently the Manga on MangaDex was deleted, because I can no longer access it. It was still on my reading list.
> 
> It was:
> https://mangadex.org/title/42110/the-archmage-s-daughter

It's not deleted, you cant access that manga without logging in. And since my MD scraper (my api) operates without login it doesn't know the manga exists hence why you're getting the discrepancy. I'll see what I can do. Open a separate issue for this
