### ISSUE TITLE
[BUG] User set Validity Duration not saving

### ISSUE THREAD

**Issue by Jdelli1** [FaizanDurrani/MDReader-Builds#408]
**Describe the bug**
Under security the validity duration does not save the time specified by user. Tried going back to settings to see if that would save the user input. 

**To Reproduce**
Change the time under validity duration. Close the app.

**Expected behaviour**
Save the time set by user requiring FaceID/Fingerprint/Password after the app is closed.

**App Version**
Eg: v0.6.0-r2.0.20
Running on iPhone 8+ IOS 15.0

**Comment by Jdelli1** [comment]
This is still apparent in v0.6.2-r1.0.0

**Comment by FaizanDurrani** [comment]
Added in 0.7 Build 16
