### ISSUE TITLE
[BUG] App crashes when side-scrolling on Discover

### ISSUE THREAD

**Issue by SirNoodly** [FaizanDurrani/MDReader-Builds#51]
**Describe the bug**
App crashes when side-scrolling on any of the three Discover sections. 

**To Reproduce**
1. Open app. 
2. (Optional) Wait until initial page appears to have finished loading. 
3. Scroll sideways on Latest Updates, Featured Titles, or New Releases. 

**Expected behaviour**
Scrolling shouldn’t crash application. 

**App Version**
v0.2-wip.6.1

**Screenshots**

**Comment by FaizanDurrani** [comment]
Which iOS version are you on?

**Comment by SirNoodly** [comment]
13.4.1

**Comment by FaizanDurrani** [comment]
Let me know if the issue is fixed in the latest WIP build

**Comment by SirNoodly** [comment]
Yep, fixed! Thanks!
