### ISSUE TITLE
[REQUEST] Choose your reading language(s) in the settings

### ISSUE THREAD

**Issue by Pixelatex** [FaizanDurrani/MDReader-Builds#62]
**Description**
Indicate your reading languages and only show the latest updates/searches/etc in those.
Ideally, this should be a setting so you don't have to filter/search this every time.

**How would it improve the App?**

Most people generally can only read one or maybe two languages so it makes very little sense to show all the updates in all possible languages. This will help curate the content for your specifications.

**Comment by FaizanDurrani** [comment]
Already implemented. Go to settings > content settings. Make sure you login with MD (with remember me) to not have them reset every time you launch the app.

**Comment by humzakh** [comment]
@FaizanDurrani 
Commenting here to point out that there is no "Content Settings" on iPad. I'm trying to read a manga of which there are several languages. Once I finish reading a chapter in English, the next one is in one of the other languages.

I tried downloading all of the English chapters, but it seems that there is no way to show only downloaded chapters. Even clicking the "Downloaded Manga" tab and opening the manga continues to show all of the other languages, despite having all the English chapters downloaded.
