### ISSUE TITLE
[BUG] Language prefrences reset on relaunch?

### ISSUE THREAD

**Issue by acknologia** [FaizanDurrani/MDReader-Builds#64]
**Describe the bug**
Whenever the app gets relaunched by the ipad by itself and not manually, my language settings reset to all languages. 
**To Reproduce**
i think by having the app open, locking the device and coming back a bunch of hours later.

**Expected behaviour**
Language settings reset to all languages

**App Version**
Eg: v0.2-wip.3.1

**Screenshots**

**Comment by FaizanDurrani** [comment]
Login with MD (tick "remember me") and make sure your email is verified on the account.

**Comment by acknologia** [comment]
I actually still get the error with a verified account that is set to remember me.

**Comment by FaizanDurrani** [comment]
Try changing the language from the website then. Go to MangaDex on safari and change your language from the settings menu in the top right.

Then logout from the app and login again.
